# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  run-ubuntu:
    docker:
      - image: ubuntu:18.04
    working_directory: /home/stephen2m/repo

    steps:
      - checkout
      - run:
          name: List Directory Contents
          command: |
            pwd; ls -lsha
      - run:
          name: Provision OS
          command: |
            bash tasks/debian/01_osprep.sh
#      - run:
#          name: Setup git
#          command: |
#            bash tasks/common/01_git.sh
#      - run:
#          name: Setup java
#          command: |
#            bash tasks/common/02_java.sh
#      - run:
#          name: Setup npm
#          command: |
#            bash tasks/common/03_npm.sh
#      - run:
#          name: Setup ruby
#          command: |
#            bash tasks/common/04_ruby.sh
#      - run:
#          name: Setup AWS tools
#          command: |
#            bash tasks/common/05_aws.sh

      - store_artifacts:
          path: logs

  run-arch-linux:
    docker:
      - image: oddlid/arch-desktop
    working_directory: /home/stephen2m/repo

    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: Provision OS
          command: |
            bash tasks/arch/01_osprep.sh

      - store_artifacts:
          path: logs

workflows:
  version: 2
  provision-environment:
    jobs:
      - run-ubuntu
